import type { ControlPlanView } from "./types";

export const CONTROL_PLANS: ControlPlanView[] = [
  {
    id: "cp1",
    name: "Contrôle rentrée scolaire",
    description:
      "Opération de contrôle à grande échelle sur l'ensemble du réseau tram et bus pour la rentrée scolaire. Coordination multi-équipes sur les axes à forte affluence.",
    objective: "Lutte contre la fraude",
    priority: "high",
    status: "active",
    start_date: "2025-09-15",
    end_date: "2025-09-21",
    created_by: "regulator-ttx",
    manager: "Régulateur TTX",
    missionCount: 12,
    teamCount: 4,
    agentCount: 18,
    zoneCount: 7,
    networks: ["BLX", "TTX"],
    lines: ["T1", "T2", "T3", "Bus C3", "Bus C4"],
    stations: ["Commerce", "Haluchère", "Gare Nord", "Beaujoire", "Doulon"],
    zoneLabels: ["Nord", "Centre", "Sud", "Ouest", "Est", "Haluchère", "Beaujoire"],
    timeSlots: [
      { label: "Matin", start: "06:30", end: "10:00" },
      { label: "Midi", start: "11:30", end: "14:00" },
      { label: "Soir", start: "16:30", end: "20:00" },
    ],
    vehicles: ["Véhicule MSR-01", "Véhicule MSR-02"],
    equipment: ["Lecteurs NFC", "Gilets haute visibilité", "Talkies-walkies"],
    instructions: [
      "Renforcer la présence visible sur les quais",
      "Vérifier systématiquement les titres de transport",
      "Remonter tout incident via l'application en temps réel",
      "Coordonner avec les équipes de régulation",
    ],
    metrics: {
      coverageRate: 87,
      incidentsReported: 14,
      completionRate: 72,
      activeAgents: 15,
    },
    missions: [
      {
        id: "m1",
        control_plan_id: "cp1",
        team_id: "nord",
        zone_id: "zone-nord",
        start_time: "2025-09-15T07:00:00",
        end_time: "2025-09-15T11:00:00",
        status: "in_progress",
        teamName: "Équipe Nord",
        zoneLabel: "Commerce → Haluchère",
        title: "Contrôle Ligne T1",
      },
      {
        id: "m2",
        control_plan_id: "cp1",
        team_id: "centre",
        zone_id: "zone-centre",
        start_time: "2025-09-15T08:00:00",
        end_time: "2025-09-15T12:00:00",
        status: "in_progress",
        teamName: "Équipe Centre",
        zoneLabel: "Centre historique",
        title: "Surveillance Centre-ville",
      },
      {
        id: "m3",
        control_plan_id: "cp1",
        team_id: "sud",
        zone_id: "zone-sud",
        start_time: "2025-09-16T14:00:00",
        end_time: "2025-09-16T18:00:00",
        status: "planned",
        teamName: "Équipe Sud",
        zoneLabel: "Gare Sud → Zénith",
        title: "Sécurité Ligne T2",
      },
      {
        id: "m4",
        control_plan_id: "cp1",
        team_id: "ouest",
        zone_id: "zone-ouest",
        start_time: "2025-09-17T07:00:00",
        end_time: "2025-09-17T11:00:00",
        status: "planned",
        teamName: "Équipe Ouest",
        zoneLabel: "Beaujoire → Doulon",
        title: "Contrôle matinal Ouest",
      },
    ],
  },
  {
    id: "cp2",
    name: "Opération Match Beaujoire",
    description: "Plan de contrôle dédié aux événements sportifs à la Beaujoire.",
    objective: "Gestion des flux voyageurs",
    priority: "medium",
    status: "completed",
    start_date: "2025-06-10",
    end_date: "2025-06-12",
    created_by: "regulator-ttx",
    manager: "Régulateur TTX",
    missionCount: 6,
    teamCount: 3,
    agentCount: 12,
    zoneCount: 3,
    networks: ["TTX"],
    lines: ["T1", "Bus E3"],
    stations: ["Beaujoire", "Haluchère"],
    zoneLabels: ["Beaujoire", "Haluchère", "Doulon"],
    timeSlots: [{ label: "Événement", start: "17:00", end: "23:00" }],
    vehicles: ["Véhicule MSR-03"],
    equipment: ["Talkies-walkies"],
    instructions: ["Gestion des flux sortants", "Coordination forces de l'ordre"],
    metrics: {
      coverageRate: 95,
      incidentsReported: 3,
      completionRate: 100,
      activeAgents: 0,
    },
    missions: [],
  },
  {
    id: "cp3",
    name: "Contrôle nocturne réseau",
    description: "Patrouilles de fin de soirée sur les dessertes à faible fréquentation.",
    objective: "Sécurisation nocturne",
    priority: "low",
    status: "draft",
    start_date: "2025-10-01",
    end_date: "2025-10-31",
    created_by: "regulator-ttx",
    manager: "Régulateur TTX",
    missionCount: 0,
    teamCount: 2,
    agentCount: 8,
    zoneCount: 4,
    networks: ["BLX"],
    lines: ["Bus C4", "Bus 12"],
    stations: ["Doulon", "Ranzay"],
    zoneLabels: ["Sud", "Est"],
    timeSlots: [{ label: "Nuit", start: "22:00", end: "02:00" }],
    vehicles: [],
    equipment: ["Lampes torches"],
    instructions: ["Rapport de fin de mission obligatoire"],
    metrics: {
      coverageRate: 0,
      incidentsReported: 0,
      completionRate: 0,
      activeAgents: 0,
    },
    missions: [],
  },
  {
    id: "cp4",
    name: "Plan anti-fraude T1",
    description: "Contrôles ciblés sur la ligne T1 en période de forte affluence.",
    objective: "Lutte contre la fraude",
    priority: "high",
    status: "suspended",
    start_date: "2025-08-01",
    end_date: "2025-08-15",
    created_by: "regulator-ttx",
    manager: "Thomas Martin",
    missionCount: 8,
    teamCount: 2,
    agentCount: 10,
    zoneCount: 5,
    networks: ["TTX"],
    lines: ["T1"],
    stations: ["Commerce", "Gare Maritime", "Haluchère"],
    zoneLabels: ["Nord", "Centre"],
    timeSlots: [
      { label: "Pointe", start: "07:00", end: "09:30" },
      { label: "Pointe", start: "17:00", end: "19:30" },
    ],
    vehicles: ["Véhicule MSR-01"],
    equipment: ["Lecteurs NFC"],
    instructions: ["Contrôle montée à bord systématique"],
    metrics: {
      coverageRate: 45,
      incidentsReported: 8,
      completionRate: 38,
      activeAgents: 0,
    },
    missions: [],
  },
];

export const CONTROL_PLAN_KPI = {
  activePlans: 2,
  totalMissions: 26,
  agentsMobilized: 48,
  coverageRate: 82,
  criticalAlerts: 1,
};
