/**
 * Schémas lignes BLX 2025-2026 — Dépôt Le Bêle (Semitan)
 * Source : SCHEMAS_LIGNES_BLX_2025-2026.pdf
 */

import type { DepotInfo, DepotLine } from "@/lib/depot-types";

export type BeleDepotLine = DepotLine;

export const BELE_DEPOT = {
  code: "BLX",
  name: "Le Bêle",
  operator: "Semitan",
  season: "2025-2026",
} as const satisfies DepotInfo;

export const BELE_DEPOT_LINES: BeleDepotLine[] = [
  {
    id: "10",
    shortName: "10",
    origin: "Bd de Boulon",
    destination: "Gare de Chantenay",
    lineColor: "#FFED00",
    depotCode: "BLX",
    stops: [
      "Toutes Aides",
      "Lombarderie",
      "Lemoine",
      "Rd Pt de Paris",
      "Michelet",
      "St Jean Baptiste",
      "De la Salle",
      "Rd Pt Rennes",
      "Rd Pt Vannes",
      "Bd des Anglais",
      "Poincaré",
      "Zola",
      "Egalité",
      "Jean Macé",
      "Bas Chantenay",
      "Gare de Chantenay",
    ],
  },
  {
    id: "11",
    shortName: "11",
    origin: "Perray",
    destination: "Tertre",
    lineColor: "#E8B975",
    depotCode: "BLX",
    stops: [
      "Perray",
      "Patis Rondin",
      "Pré Hervé",
      "Pin Sec",
      "Fresnel",
      "Menetrier",
      "Bottière",
      "Marrière",
      "Bois Robillard",
      "Mitrie",
      "Dalby",
      "Casterneau",
      "Pipay",
      "Gambetta",
      "Bouteillerie",
      "Foch",
      "Place du Cirque",
      "St Nicolas",
      "Lamoricère",
      "Canclaux",
      "René Bouhier",
      "Mellinet",
      "Zola",
      "Egalité",
      "Mairie de Chantenay",
      "Netto",
      "Jean Moulin",
      "Croix Bonneau",
      "Plaine de Jeux",
      "Petit Breton",
      "Tertre",
    ],
  },
  {
    id: "23",
    shortName: "23",
    origin: "Haluchère",
    destination: "Mendès France - Bellevue",
    lineColor: "#0BBBEF",
    depotCode: "BLX",
    stops: [
      "Haluchère",
      "Koufra",
      "Ranzay",
      "Les Salles",
      "Eraudière",
      "Michelet",
      "St Jean Baptiste",
      "De la Salle",
      "Rd Pt Rennes",
      "50 Otages",
      "Place du Cirque",
      "St Nicolas",
      "Canclaux",
      "Mellinet",
      "Zola",
      "Cimetière",
      "St Clair",
      "Danais",
      "Repos de Chasse",
      "Branchoire",
      "Neruda",
      "Maison des Arts",
      "MF-Bellevue",
    ],
  },
  {
    id: "85",
    shortName: "85",
    origin: "Haluchère",
    destination: "Souchais",
    lineColor: "#F5B5D3",
    depotCode: "BLX",
    stops: [
      "Haluchère",
      "Clétras",
      "Noé Blanche",
      "Marché Commun",
      "Sercel",
      "Mainguais",
      "Jumelière",
      "Ladoumègue",
      "Marquis de Dion",
      "Centre de Carquefou",
      "Schweitzer",
      "Aristide Briand",
      "Fleuriaye",
      "Renaudières",
      "Arago",
      "Danube",
      "Souchais",
    ],
  },
  {
    id: "86",
    shortName: "86",
    origin: "Bout des Pavés",
    destination: "La Chapelle Aulnay",
    lineColor: "#0BBBEF",
    depotCode: "BLX",
    stops: [
      "Bout des Pavés",
      "Monge",
      "Chauvinière",
      "Vincent Scotto",
      "Recteur Schmitt",
      "Bourgeonnière",
      "Porte de la Chapelle",
      "Gesvres",
      "Mulonnière",
      "Gesvrine",
      "Crétinières",
      "Capellia",
      "Vrière",
      "La Cogne",
      "Mongendière",
      "Poste",
      "Léo Lagrange",
      "Gillieres",
      "Ploreau",
      "La Source",
      "Perrières",
      "La Chapelle Aulnay",
    ],
  },
  {
    id: "C1",
    shortName: "C1",
    origin: "Haluchère",
    destination: "Gare de Chantenay",
    lineColor: "#0BBBEF",
    depotCode: "BLX",
    stops: [
      "Haluchère",
      "Croissant",
      "Rond Point de Paris",
      "Desaix",
      "Chanzy",
      "St Clément",
      "Foch",
      "Place du Cirque",
      "St Nicolas",
      "Lamoricère",
      "Canclaux",
      "Mellinet",
      "Lechat",
      "Lusancay",
      "Jean Macé",
      "Bas Chantenay",
      "Gare de Chantenay",
    ],
  },
  {
    id: "C6",
    shortName: "C6",
    origin: "Chantrerie",
    destination: "Hermeland",
    lineColor: "#A877B2",
    depotCode: "BLX",
    stops: [
      "Chantrerie",
      "Moulin de Porterie",
      "Eraudière",
      "St Joseph de Porterie",
      "Embellie",
      "Linot",
      "Beaujoire",
      "Ranzay",
      "Belges",
      "Montbazon",
      "Bonde",
      "Foch",
      "Place du Cirque",
      "St Nicolas",
      "Delorme",
      "Mondésir",
      "Doumer",
      "Poincaré",
      "Vincent Auriol",
      "St Laurent",
      "Dervallières",
      "Tillay",
      "Polyclinique",
      "Hermeland",
    ],
  },
  {
    id: "C7",
    shortName: "C7",
    origin: "Souillarderie",
    destination: "Clairais / Trianon",
    lineColor: "#C8D300",
    depotCode: "BLX",
    stops: [
      "Souillarderie",
      "Cousteau",
      "Basse Chenaie",
      "Vesprées",
      "Bois des Anses",
      "Coty",
      "Planchonnais",
      "Bougrière",
      "Pont de la Metairie",
      "Point du Jour",
      "Parc des Sports",
      "Minais",
      "Centre de Thouare",
      "Clairais",
      "Trianon",
      "Maurriène",
      "Pré Poulain",
      "Bussonnière",
    ],
  },
];

export const BELE_CUT_POINTS = [
  "Bertrand Geslin",
  "Copernic Musée",
  "Delorme",
  "Edit de Nantes",
  "Foch",
  "Bouteillerie",
  "Gare Nord",
  "Duchesse Anne",
  "Talensac",
  "Chanzy",
  "Breteche",
  "Lallié",
  "Desaix",
] as const;

const BELE_LINE_IDS = new Set(BELE_DEPOT_LINES.map((l) => l.id));

export function isBeleDepotLine(routeId: string): boolean {
  return BELE_LINE_IDS.has(routeId);
}

export function getBeleDepotLine(routeId: string): BeleDepotLine | undefined {
  return BELE_DEPOT_LINES.find((l) => l.id === routeId);
}

export function getBeleDepotLineIds(): string[] {
  return BELE_DEPOT_LINES.map((l) => l.id);
}
