/**
 * Schémas lignes SHX 2025-2026 — Dépôt Semitan (modèle SHX)
 * Source : Schémas Lignes SHX_Modèle 2025-2026.pdf
 */

import type { DepotInfo, DepotLine } from "@/lib/depot-types";

export const SHX_DEPOT: DepotInfo = {
  code: "SHX",
  name: "Semitan",
  operator: "Semitan",
  season: "2025-2026",
};

export const SHX_DEPOT_LINES: DepotLine[] = [
  {
    id: "12",
    shortName: "12",
    origin: "Beauséjour",
    destination: "Jules Verne",
    lineColor: "#E8B975",
    depotCode: "SHX",
    stops: [
      "Beauséjour",
      "Rond Point De Rennes",
      "Préfecture",
      "Hôtel de Ville",
      "Place Foch",
      "Cimetière Bouteillerie",
      "Rue de Pipay",
      "Feu de Dalby",
      "Parc de Mitrie",
      "Toutes Aides",
      "Mairie de Doulon",
      "Parc du Grand Blotereau",
      "Vieux Doulon",
      "Colinière",
      "Leclerc Paridis",
      "Jules Verne",
    ],
  },
  {
    id: "50",
    shortName: "50",
    origin: "Basse Indre",
    destination: "Porte de la Chapelle",
    lineColor: "#EF4444",
    depotCode: "SHX",
    stops: [
      "Basse Indre",
      "Mairie Basse Indre",
      "François Mitterrand",
      "Mairie St Herblain",
      "Marcel Paul",
      "Porte de la Chapelle",
    ],
  },
  {
    id: "69",
    shortName: "69",
    origin: "Sautron",
    destination: "Orvault Morlière",
    lineColor: "#A877B2",
    depotCode: "SHX",
    stops: [
      "Sautron",
      "La Ferme",
      "Super U",
      "Lidl",
      "Porsche",
      "Lycée Riefel",
      "Rd pt José Arribas",
      "Rd pt du Croisy",
      "Orvault Morlière",
    ],
  },
  {
    id: "86",
    shortName: "86",
    origin: "Bout des Pavés",
    destination: "Chapelle Aulnay",
    lineColor: "#0BBBEF",
    depotCode: "SHX",
    stops: [
      "Bout des Pavés",
      "Poste",
      "Porte de la Chapelle",
      "Bourgeonnière",
      "Gesvrines",
      "Rod Point Ovale",
      "La Cogne",
      "Château d'eau",
      "Gilière",
      "La Source",
      "Pérrières",
      "Plessis",
      "Chapelle Aulnay",
    ],
  },
  {
    id: "C2",
    shortName: "C2",
    origin: "Le Cardo",
    destination: "Gare Sud",
    lineColor: "#2563EB",
    depotCode: "SHX",
    stops: [
      "Le Cardo",
      "Rond Point de Rennes",
      "Commerce",
      "Préfecture",
      "Hôtel Dieu",
      "Quai Baco",
      "Gare Sud",
    ],
  },
  {
    id: "C3",
    shortName: "C3",
    origin: "Bd de Doulon",
    destination: "Armor",
    lineColor: "#22C55E",
    depotCode: "SHX",
    stops: [
      "Bd de Doulon",
      "Haubans",
      "Gare Sud",
      "San Francisco",
      "Commerce",
      "Saint Nicolas",
      "Delorme",
      "Canclaux",
      "Parc de Procès",
      "Vincent Auriol",
      "Rond point Châtaignier",
      "Clinique de la Main",
      "Armor",
    ],
  },
  {
    id: "C8",
    shortName: "C8",
    origin: "Marcel Paul",
    destination: "Saupin",
    lineColor: "#F59E0B",
    depotCode: "SHX",
    stops: [
      "Marcel Paul",
      "Grand Carcouet",
      "Lycée Carcouet",
      "Parc de Procès",
      "Toutes Joies",
      "Anatole France",
      "Saint Nicolas",
      "Commerce",
      "Quai Baco",
      "Gare Sud Saupin",
    ],
  },
  {
    id: "C20",
    shortName: "C20",
    origin: "Ecole centrale Audencia",
    destination: "Gare Maritime",
    lineColor: "#6366F1",
    depotCode: "SHX",
    stops: [
      "Ecole centrale Audencia",
      "Piscine du Petit Port",
      "Hippodrome",
      "Petit Port",
      "Pont du Cens",
      "Beauséjour",
      "Grand Carcouet",
      "Rond Point des Châtaigniers",
      "Janvraie",
      "Gare de Chantenay",
      "Jardin Extraordinaire",
      "Gare Maritime",
    ],
  },
];
