/**
 * Schémas lignes TTX 2025-2026 — Dépôt Trentemoult (Semitan)
 * Source : Schémas Lignes TTX 2025-2026.pdf
 */

import type { DepotInfo, DepotLine } from "@/lib/depot-types";

export const TTX_DEPOT: DepotInfo = {
  code: "TTX",
  name: "Trentemoult",
  operator: "Semitan",
  season: "2025-2026",
};

export const TTX_DEPOT_LINES: DepotLine[] = [
  {
    id: "5",
    shortName: "5",
    origin: "Gare Sud",
    destination: "Hangar à Bananes",
    lineColor: "#A877B2",
    depotCode: "TTX",
    stops: [
      "Gare Sud",
      "Conservatoire",
      "Île de Nantes",
      "Haubans",
      "Gare de l'Etat",
      "Nizan",
      "Vincent Gâche",
      "Quai des Antilles",
      "Hangar à Bananes",
    ],
  },
  {
    id: "26",
    shortName: "26",
    origin: "Hôtel de Région",
    destination: "Jonelière",
    lineColor: "#2563EB",
    depotCode: "TTX",
    stops: [
      "Hôtel de Région",
      "Mandel",
      "Mangin",
      "Gustave Roch",
      "République",
      "Gaston Veil",
      "Commerce",
      "Sébilleau",
      "Mondésir",
      "Delorme",
      "St Nicolas",
      "Toutes Joies",
      "Anatole France",
      "Rp de Rennes",
      "Morrhonnière",
      "Félix Faure",
      "Petit Port",
      "Bourgeonnière",
      "Recteur Schmitt",
      "Vincent Scotto",
      "Jonelière",
    ],
  },
  {
    id: "30",
    shortName: "30",
    origin: "Îles de Loire",
    destination: "Trentemoult",
    lineColor: "#22C55E",
    depotCode: "TTX",
    stops: [
      "Îles de Loire",
      "Savarières",
      "St Sébastien",
      "Villeneuve",
      "Patis Brûlé",
      "Largeau",
      "Radigois",
      "St Jean",
      "Joliverie",
      "Bourdonnières",
      "Marterie",
      "La Carrée",
      "Espace Diderot",
      "Le Corbusier",
      "Mahaudières",
      "Californie",
      "Mairie de Rezé",
      "Seil",
      "Quai Surcouf",
      "Trentemoult",
    ],
  },
  {
    id: "36",
    shortName: "36",
    origin: "Greneraie",
    destination: "Croix Jeannette",
    lineColor: "#F59E0B",
    depotCode: "TTX",
    stops: [
      "Greneraie",
      "Pirmil",
      "LIDL",
      "Basse Île",
      "Leclerc",
      "Trentemoult",
      "Paix",
      "Neustrie",
      "Bastille",
      "Piano'cktail",
      "Centre de Bouguenais",
      "Allende",
      "Croix Jeannette",
    ],
  },
  {
    id: "38",
    shortName: "38",
    origin: "Greneraie",
    destination: "Aéroport",
    lineColor: "#FFED00",
    depotCode: "TTX",
    stops: [
      "Greneraie",
      "Pirmil",
      "Paix",
      "AIRBUS",
      "Brossais",
      "Bélouga",
      "Porte de Retz",
      "Moulin à l'Huile",
      "Aéroport",
    ],
  },
  {
    id: "97",
    shortName: "97",
    origin: "Vertou",
    destination: "Trentemoult",
    lineColor: "#0BBBEF",
    depotCode: "TTX",
    stops: [
      "Vertou",
      "Bretonnière",
      "Rocade",
      "Le Chêne",
      "Port aux Meules",
      "L'Ebaupin",
      "Rousselière",
      "Marterie",
      "Jean Fraix",
      "Felix Tableau",
      "8 Mai",
      "Mahaudière",
      "Le Corbusier",
      "Seil",
      "Trentemoult",
    ],
  },
  {
    id: "98",
    shortName: "98",
    origin: "Neustrie",
    destination: "Gare de Bouaye",
    lineColor: "#F5B5D3",
    depotCode: "TTX",
    stops: [
      "Neustrie",
      "Porte de Grand Lieu",
      "Aéroclub",
      "D2A Aéroport",
      "Lindbergh",
      "Champ de Foire",
      "Jahardières",
      "Noé Nozou",
      "Beauvaiserie",
      "Jouetterie",
      "Gare de Bouaye",
    ],
  },
  {
    id: "C4",
    shortName: "C4",
    origin: "Greneraie",
    destination: "Les Sorinières",
    lineColor: "#14B8A6",
    depotCode: "TTX",
    stops: [
      "Greneraie",
      "Pirmil",
      "Felix Tableau",
      "Trois Moulins",
      "La Carrée",
      "Corbinerie",
      "Mairie des Sorinières",
      "Champ Fleuri",
      "Papillon",
      "Prière",
      "Les Sorinières",
    ],
  },
  {
    id: "C9",
    shortName: "C9",
    origin: "Pirmil",
    destination: "Basse Goulaine",
    lineColor: "#C8D300",
    depotCode: "TTX",
    stops: [
      "Pirmil",
      "Greneraie",
      "Baugerie",
      "St Sébastien",
      "Savarières",
      "Quintaine",
      "Basse Goulaine",
    ],
  },
];
